---
#change hosts to [apache servers] when deployed
- hosts: 172.28.128.3
  become: yes
  become_user: root
  gather_facts: yes
#can use sudo/sudo_user instead of become, but thats depreceated in ansible 2.6 or later
  tasks:  
    - name: create keys
      command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
 
- hosts: [nodes]
  tasks:
    - name: send key to nodes
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  



     

    
